workflows:
  default-workflow:
    name: Universal APK Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter dependencies installation
        script: |
          flutter pub get
      - name: Flutter build Universal APK
        script: |
          # A sima build alapból egy univerzális FAT APK fájlt hoz létre
          flutter build apk --release
    artifacts:
      # Ez a pontos elérése a létrejövő egyetlen univerzális APK-nak
      - build/app/outputs/flutter-apk/app-release.apk
