workflows:
  default-workflow:
    name: Universal APK Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter dependencies installation
        script: |
          flutter pub get
      - name: Flutter build Universal APK
        script: |
          # A --no-split-per-abi kényszeríti ki, hogy minden processzortípus benne legyen az APK-ban
          flutter build apk --release --no-split-per-abi
    artifacts:
      # Ez a pontos elérése az elkészült univerzális APK fájlnak
      - build/app/outputs/flutter-apk/app-release.apk
